name: Publish Docker Image

on:
  push:
    branches:
      - release/**

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: microwebteam/github-action-docker-build@master
        with:
          name: traefik-proxy
        env:
          GITHUB_TOKEN: ${{ secrets.GLOBAL_GITHUB_TOKEN }}
